feat(github/workflow/ci.yml): add build and tests workflows

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,6 +28,47 @@ jobs:
           echo "Clang-format errors detected:"
           cat ./clang-format-errors.txt
 
+  build:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: Set up C++ environment
+        uses: actions/setup-cpp@v1
+        with:
+          compiler: 'gcc' # or 'clang'
+      - name: Build project
+        run: |
+          chmod +x ./tools.sh
+          ./tools.sh build
+
+  tests:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: Set up C++ environment
+        uses: actions/setup-cpp@v1
+        with:
+          compiler: 'gcc' # or 'clang'
+      - name: Run tests
+        run: |
+          chmod +x ./tools.sh
+          ./tools.sh test | tee test-results.txt
+      - name: Check test results
+        run: |
+          if grep -q "FAILED" test-results.txt; then
+            echo "Tests failed"
+            exit 1
+          else
+            echo "Tests passed"
+          fi
+
   push-to-mirror:
     runs-on: ubuntu-latest
     if: github.ref == 'refs/heads/main' && success()
